spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: customize-form
  datasource:
    url: jdbc:mysql://localhost:3306/customize-form?useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=UTF8&allowMultiQueries=true
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 1
    encoding: UTF-8
    out-of-order: false
    schemas: customize-form
    validate-on-migrate: false

server:
  port: 9999
