spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: customize-form
  datasource:
    url: jdbc:${DB_URL}?useUnicode=true&autoReconnect=true&useSSL=false&characterEncoding=UTF8&allowMultiQueries=true
    username: ${DB_USER}
    password: ${DB_PWD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  flyway:
    enabled: true
    clean-disabled: true
    locations: classpath:db/migration
    table: flyway_schema_history
    baseline-on-migrate: true
    baseline-version: 1
    encoding: UTF-8
    out-of-order: false
    schemas: spcjsh2oabytktw2
    validate-on-migrate: false

server:
  port: 9999
